/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task.manager;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author George
 */
public class MainWindow extends javax.swing.JFrame {

    NewTaskDialog ntd = new NewTaskDialog(this, true);
    
    ArrayList<Task> tasks = new ArrayList<>();
    boolean isDirty = false;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        //tasks.add(new Task(Task.Prio.MEDIUM,"Add To-Do Functions",""));
         
        tasks = new ArrayList<>();
        
        try(BufferedReader br = new BufferedReader(new FileReader("C:/tmp/to-do.list"))) {
            String line;
            while((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                tasks.add(new Task(Task.Prio.valueOf(parts[0]),parts[1],""));
            }
            
            updateList();
        } catch (IOException ioex) {
            
        }
        updateList();
    }
    
    public final void updateList() {
        String[] tasksString = new String[tasks.size()];
        
        //tasks.add(new Task(Task.Prio.MEDIUM,"Add To-Do Functions",""));
        
        for(int i = 0; i < tasks.size(); i++) tasksString[i] = tasks.get(i).getTitle();        
        lstTasks.setListData(tasksString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTasks = new javax.swing.JList<>();
        txtfName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDesc = new javax.swing.JTextArea();
        btnComplete = new javax.swing.JButton();
        cmbPrio = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstTasks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTasks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTasksValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTasks);

        txtfName.setText("Task Name");
        txtfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfNameFocusLost(evt);
            }
        });

        txtaDesc.setColumns(20);
        txtaDesc.setRows(5);
        txtaDesc.setText("Task Description\n");
        txtaDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtaDescFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txtaDesc);

        btnComplete.setText("Mark As Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        cmbPrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HIGH", "MEDIUM", "LOW"}));
        cmbPrio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbPrioFocusLost(evt);
            }
        });

        btnAdd.setText("Add New Task");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Save...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Load...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstTasksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTasksValueChanged
        // TODO add your handling code here
        int idx = lstTasks.getSelectedIndex();
        if(idx > -1) {
            Task curr = tasks.get(lstTasks.getSelectedIndex());
            //txtaDesc.setText(curr.getDesc());
            txtfName.setText(curr.getTitle());
            cmbPrio.setSelectedIndex(curr.getPriority().ordinal());
        } else {
            //txtaDesc.setText("");
            txtfName.setText("");
            cmbPrio.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_lstTasksValueChanged

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        int idx = lstTasks.getSelectedIndex();
        
        if(idx > -1) {
            Task curr = tasks.get(idx);
            tasks.remove(curr);
            isDirty = true;
        }
        updateList();
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("C:/tmp/");
        jfc.showSaveDialog(jMenu1);
        File file = jfc.getSelectedFile();
        try(BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
           for(Task t : tasks) {
               if(t.getTitle() != null && t.getTitle().length() > 0) {
                   bw.write(t.toCSV());
                   bw.newLine();
               }
           }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("C:/tmp/");
        jfc.showSaveDialog(jMenu1);
        File file = jfc.getSelectedFile();
        
        tasks = new ArrayList<>();
        
        try(BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                tasks.add(new Task(Task.Prio.valueOf(parts[0]),parts[1],""));
            }
            
            updateList();
        } catch (IOException ioex) {
            
        }
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfNameFocusLost
        // TODO add your handling code here:
        
        updateTask();
        updateUI();
        
        
    }//GEN-LAST:event_txtfNameFocusLost

    private void txtaDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaDescFocusLost
        // TODO add your handling code here:
        updateTask();
        updateUI();
    }//GEN-LAST:event_txtaDescFocusLost

    private void cmbPrioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbPrioFocusLost
        // TODO add your handling code here:
        updateTask();
        updateUI();
    }//GEN-LAST:event_cmbPrioFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        updateTask();
        updateList();
        updateUI();
    }//GEN-LAST:event_btnAddActionPerformed

    
    public void updateUI() {
        int idx = lstTasks.getSelectedIndex();
        if(idx > -1) {
            Task curr = tasks.get(idx);
            //txtaDesc.setText(curr.getDesc());
            txtfName.setText(curr.getTitle());
            cmbPrio.setSelectedIndex(curr.getPriority().ordinal());
            
        } 
        
        updateList();
    }
    
    public void updateTask() {
        int idx = lstTasks.getSelectedIndex();
        
        if(idx > -1) {
            Task curr = tasks.get(idx);
            curr.setPriority(Task.Prio.values()[cmbPrio.getSelectedIndex()]);
            curr.setTitle(txtfName.getText());
        } else {
            tasks.add(new Task(Task.Prio.values()[cmbPrio.getSelectedIndex()],txtfName.getText(),""));
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //System.out.println(javax.swing.UIManager.getInstalledLookAndFeels());
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info);
                if ("Metal".equals(info.getName())) {
                    
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnComplete;
    private javax.swing.JComboBox<String> cmbPrio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstTasks;
    private javax.swing.JTextArea txtaDesc;
    private javax.swing.JTextField txtfName;
    // End of variables declaration//GEN-END:variables
}
